site_name: Accueil
site_description: Le glossaire Le Nordestês

extra_css:
- estilo.css

nav:
- Les Oeuvres: essai.md
- L'espace géographique: espace.md
- Le langage: langage.md
- Du Nordestês : mots.md
- Contactez-nous : contacte.md

